apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-world-chart.fullname" . }}
spec:
  selector:
    app: hello-world
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 8080
  type: {{ .Values.service.type }}
